trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: DockerCreds		#Variable Group to store Creds	
steps:  
- task: PowerShell@2
  displayName: Build
  inputs:
    targetType: 'inline'
    script: |
      docker build -t dennyq .
    workingDirectory: '$(Build.SourcesDirectory)'
  
- task: PowerShell@2
  displayName: Tag
  inputs:
    targetType: 'inline'
    script: |
      docker tag dennyq aviii9643/demo123458
    workingDirectory: '$(Build.SourcesDirectory)'

- task: PowerShell@2
  displayName: Log-in                   	# for ACR password will be Access key
  inputs:
    targetType: 'inline'
    script: |
     sudo docker login -u aviii9643 -p dckr_pat_Iz4Hh75PDhJTUDlwTU-cEaiT1Yk
     sudo docker push aviii9643/demo123458
    workingDirectory: '$(Build.SourcesDirectory)'

- task: PowerShell@2
  displayName: 'Deploy to OpenShift'
  inputs:
    targetType: 'inline'
    script: |
      oc login --token=sha256~jG104gYMDgFxG4DPQv2ibxn8BmuokrRT2wBE4I_GyWY --server=https://api.sandbox-m3.1530.p1.openshiftapps.com:6443
      oc project abhinavkataria12345-dev
      oc new-app mydummapp
      oc expose service mydummapp
    workingDirectory: '$(Build.SourcesDirectory)'
